### ISSUE TITLE
I can't find deployer_helm_base publicly available.

### ISSUE THREAD

**Issue by depohmel** [GoogleCloudPlatform/marketplace-k8s-app-example#71]
Actually, I can't find most of the images anywhere publicly available. 
Instead of building image and storing it in our repo I would love just to 
```FROM some_gcr/deployer_helm_base```

I see some tools, makefiles and docker files across 4 different GitHub repos and sub-modules, just docker image would be amazing.

**Comment by huyhg** [comment]
Images are now public under `gcr.io/cloud-marketplace-tools/k8s`.
